import { defineConfig } from '@umijs/max';

export default defineConfig({
  esbuildMinifyIIFE: true,
  antd: {},
  access: {},
  model: {},
  initialState: {},
  request: {},
  layout: {
    title: '奥吉通集采系统',
  },
  routes: [
    {
      path: '/',
      redirect: '/home',
      component: './Home',
    },
    {
      name: '首页',
      path: '/home',
      component: './Home',
      hideInMenu: true,
      access: 'home',
    },
    {
      name: '用户信息',
      path: '/user-info',
      component: './UserInfo',
      access: 'home',
      hideInMenu: true,
    },
    {
      name: '登录',
      path: '/login',
      component: './Login',
      layout: false,
    },
    {
      name: '采购单列表',
      path: '/purchase',
      component: './PurchaseList',
      access: 'purchaseList',
    },
    {
      name: '采购单详情',
      path: '/purchase/:id',
      component: './PurchaseDetail',
      hideInMenu: true,
      access: 'purchaseDetail',
    },
    {
      name: '供应商报价',
      path: '/supplier-quote/:id',
      component: './SupplierQuote',
      hideInMenu: true,
      access: 'supplierPortal',
    },
    {
      name: '供应商报价列表',
      path: '/supplier-quotes',
      component: './SupplierQuoteList',
      access: 'supplierPortal',
    },
    {
      name: '供应商报价详情',
      path: '/supplier-quote-detail/:quoteNo',
      component: './SupplierQuoteDetail',
      hideInMenu: true,
      access: 'supplierPortal',
    },
    {
      name: '供应商门户',
      path: '/supplier-portal',
      component: './SupplierPortal',
      access: 'supplierPortal',
    },
    {
      name: '配件目录',
      path: '/catalog',
      component: './PartCatalog',
      access: 'partCatalog',
    },
    {
      name: '购物车',
      path: '/cart',
      component: './Cart',
      access: 'partCatalog',
    },
    {
      name: '系统管理',
      path: '/admin',
      component: './SystemAdmin',
      access: 'systemAdmin',
    },
    {
      name: '品类树管理',
      path: '/admin/category',
      component: './SystemAdmin/CategoryManagement',
      hideInMenu: true,
      access: 'systemAdmin',
    },
    {
      name: '产品管理',
      path: '/admin/product',
      component: './SystemAdmin/ProductManagement',
      hideInMenu: true,
      access: 'systemAdmin',
    },
    {
      name: '产品详情',
      path: '/admin/product/:id',
      component: './SystemAdmin/ProductManagement/Detail',
      hideInMenu: true,
      access: 'systemAdmin',
    },
    {
      name: 'SKU 详情',
      path: '/admin/sku/:id',
      component: './SystemAdmin/ProductManagement/Detail/SkuDetail',
      hideInMenu: true,
      access: 'systemAdmin',
    },
    {
      name: '品牌管理',
      path: '/admin/brand',
      component: './SystemAdmin/BrandManagement',
      hideInMenu: true,
      access: 'systemAdmin',
    },
    {
      name: 'SKU文件上传',
      path: '/admin/sku-upload',
      component: './SystemAdmin/SkuUpload',
      hideInMenu: true,
      access: 'systemAdmin',
    },
    {
      name: '公司管理',
      path: '/admin/company',
      component: './SystemAdmin/CompanyManagement',
      hideInMenu: true,
      access: 'systemAdmin',
    },
    {
      name: '门店管理',
      path: '/admin/store',
      component: './SystemAdmin/StoreManagement',
      hideInMenu: true,
      access: 'systemAdmin',
    },
    {
      name: '供应商管理',
      path: '/admin/supplier',
      component: './SystemAdmin/SupplierManagement',
      hideInMenu: true,
      access: 'systemAdmin',
    },
    {
      name: '接口管理',
      path: '/admin/access-api',
      component: './SystemAdmin/AccessApiManagement',
      hideInMenu: true,
      access: 'systemAdmin',
    },
    {
      name: '用户管理',
      path: '/admin/user',
      component: './SystemAdmin/UserManagement',
      hideInMenu: true,
      access: 'systemAdmin',
    },
    {
      name: '角色管理',
      path: '/admin/role',
      component: './SystemAdmin/RoleManagement',
      hideInMenu: true,
      access: 'systemAdmin',
    },
  ],
  npmClient: 'pnpm',
  proxy: {
    '/api': {
      // 标识需要进行转换的请求的url
      // target: 'http://59.110.38.103:8999',
      // target: 'http://192.168.8.66:8888',
      target: 'http://192.168.8.232:8888',
      changeOrigin: true, // 允许域名进行转换
    },
  },
});
